#pragma once
#ifndef DS_VERSION_H
#define DS_VERSION_H

#define _STR(v) #v
#define STR(v)  _STR(v)
#define _VER2STR(MAJOR, MINOR, PATCH, INNER) STR(MAJOR##.##MINOR##.##PATCH##.##INNER)
#define VER2STR(MAJOR, MINOR, PATCH, INNER) _VER2STR(MAJOR, MINOR, PATCH, INNER)

// version num
#define _MAJOR_VER       1
#define _MINOR_VER       1
#define _PATCH_VER       0
#define _INNER_VER       0

// file version
#define FILE_MAJOR_VER          _MAJOR_VER
#define FILE_MINOR_VER          _MINOR_VER
#define FILE_PATCH_VER          _PATCH_VER
#define FILE_INNER_VER          _INNER_VER
#define FILE_VERSION_VAL        FILE_MAJOR_VER, FILE_MINOR_VER, FILE_PATCH_VER, FILE_INNER_VER
#define FILE_VERSION_STR        VER2STR(FILE_MAJOR_VER, FILE_MINOR_VER, FILE_PATCH_VER, FILE_INNER_VER)

// product version
#define PRODUCT_MAJOR_VER       _MAJOR_VER
#define PRODUCT_MINOR_VER       _MINOR_VER
#define PRODUCT_PATCH_VER       _PATCH_VER
#define PRODUCT_INNER_VER       _INNER_VER
#define PRODUCT_VERSION_VAL     PRODUCT_MAJOR_VER, PRODUCT_MINOR_VER, PRODUCT_PATCH_VER, PRODUCT_INNER_VER
#define PRODUCT_VERSION_STR     VER2STR(PRODUCT_MAJOR_VER, PRODUCT_MINOR_VER, PRODUCT_PATCH_VER, PRODUCT_INNER_VER)

#endif // !DS_VERSION_H
